on: [push, pull_request]
name: Benchmarks
jobs:
  build_benchmarks:
    strategy:
      matrix:
        arch:
          - i686
          - x86_64
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C target-feature=+sse2,+aes -D warnings"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: ${{ matrix.arch }}-unknown-linux-gnu
          override: true

      - name: Build benches
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --benches --verbose

  benchmark:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C target-cpu=native -D warnings"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Run benchmarks
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --verbose
