on: [push, pull_request]
name: Build
jobs:
  build:
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
        arch:
          - i686
          - x86_64
          - aarch64
        include:
          - arch: i686
            target: i686-unknown-linux-gnu
            rust_features: "+sse2,+aes"
          - arch: x86_64
            target: x86_64-unknown-linux-gnu
            rust_features: "+sse2,+aes"
          - arch: aarch64
            target: aarch64-unknown-linux-gnu
            rust_features: "+neon,+aes"
        exclude:
          - arch: aarch64
            rust: stable
          - arch: aarch64
            rust: beta
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C target-feature=${{ matrix.rust_features }} -D warnings"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }} --verbose
