on: [push, pull_request]
name: Lints
jobs:
  clippy:
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - armv7-linux-androideabi
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          target: ${{ matrix.target }}
          components: clippy
      - name: Check Clippy lints
        run: cargo clippy --target ${{ matrix.target }} --verbose
