on: [push, pull_request]
name: Lints
jobs:
  clippy:
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - armv7-linux-androideabi
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
          components: clippy

      - name: Check Clippy lints
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target ${{ matrix.target }} --verbose
